version: "3"
services:
  server:
    # build:
    #   context: ../
    #   dockerfile: Dockerfile
    image: laukik2002/shoppinapp
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongohost
      - MONGO_PORT=27017
    networks:
      - shopping-service
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - shopping-service
    hostname: mongohost

networks:
  shopping-service:
    name: shopping-service

volumes:
  mongo-data:
