jenkins:
  hosts: 3.82.63.94
  vars:
    ansible_ssh_user: ubuntu
kops:
  hosts: 54.81.187.56
  vars:
    ansible_ssh_user: ubuntu
docker:
  hosts: 54.196.85.240
  vars:
    ansible_ssh_user: ubuntu
