---
- name: Install AWS CLI, kubectl, and kops
  hosts: kops
  become: yes
  tasks:

    # - name: Install unzip package
    #   apt:
    #     name: unzip
    #     state: present

    # - name: Download AWS CLI
    #   get_url:
    #     url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    #     dest: "/tmp/awscliv2.zip"
    #     mode: '0755'

    # - name: Unzip AWS CLI
    #   unarchive:
    #     src: "/tmp/awscliv2.zip"
    #     dest: "/tmp"
    #     remote_src: yes

    # - name: Install AWS CLI
    #   command: "/tmp/aws/install"

    - name: Fetch the latest stable version of kubectl
      shell: "curl -L -s https://dl.k8s.io/release/stable.txt"
      register: kubectl_version
      changed_when: false

    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'

    - name: Install kubectl
      copy:
        src: "/tmp/kubectl"
        dest: "/usr/local/bin/kubectl"
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

    - name: Download kops
      shell: >
        curl -Lo /tmp/kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64

    - name: Make kops executable
      file:
        path: "/tmp/kops"
        mode: '0755'

    - name: Move kops to /usr/local/bin
      command: "mv /tmp/kops /usr/local/bin/kops"
